version: '3.8'

services:
  web-clipboard-go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - GIN_MODE=release
    volumes:
      # Optional: mount host directory for persistent temp files
      # - ./temp:/tmp/web-clipboard-go
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-clipboard.rule=Host(`clipboard.local`)"
      - "traefik.http.services.web-clipboard.loadbalancer.server.port=5000"